version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easyeat
    ports:
      - 3306:3306
    volumes:
      - D:/workshop/Demo/mysql-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-php-myadmin
    ports:
      - 8082:80
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  sonar:
    image : sonarqube
    container_name: sonarqube
    restart: always
    ports:
      - 9000:9000
     volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/sonarqube_logs

  # easyeatservice:
  #   #image: easy-eat-service:1.0
  #   container_name: easy-eat-service-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   restart: always
  #   depends_on:
  #     - db
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/easyeat?createDatabaseIfNotExist=true
  #     SPRING_DATASOURCE_USERNAME: root
  #     SPRING_DATASOURCE_PASSWORD: root
    

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
